name: Python CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-22.04

    steps:

      - name: Checkout repository # Gets your GitHub repository onto that machine
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 # It sets up Python 3.11 on the virtual machine.
        with:
          python-version: "3.11"

      - name: Install pytest
        run: python -m pip install pytest

      - name: Run tests
        run: |
          cd scripts
          pytest